### ISSUE TITLE
Error in rendering 404 error template

### ISSUE THREAD

**Issue by sonofmun** [Capitains/flask-capitains-nemo#123]
https://github.com/Capitains/flask-capitains-nemo/blob/8d91f2c05b925a6c8ea8c997baf698c87257bc58/flask_nemo/__init__.py#L801-L840

**Comment by sonofmun** [comment]
The stacktrace:

```
404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.
[2018-07-16 13:34:15,272] ERROR in app: Exception on /fiel.pdf [GET]
Traceback (most recent call last):
  File "/home/matt/envs/formulae-nemo/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/matt/envs/formulae-nemo/lib/python3.6/site-packages/flask/app.py", line 1590, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/matt/envs/formulae-nemo/lib/python3.6/site-packages/flask/app.py", line 1573, in raise_routing_exception
    raise request.routing_exception
  File "/home/matt/envs/formulae-nemo/lib/python3.6/site-packages/flask/ctx.py", line 294, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/matt/envs/formulae-nemo/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/matt/envs/formulae-nemo/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/matt/envs/formulae-nemo/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/matt/envs/formulae-nemo/lib/python3.6/site-packages/flask/app.py", line 1512, in handle_user_exception
    return self.handle_http_exception(e)
  File "/home/matt/envs/formulae-nemo/lib/python3.6/site-packages/flask/app.py", line 1471, in handle_http_exception
    return handler(e)
  File "/home/matt/formulae-capitains-nemo/formulae/nemo.py", line 434, in e_not_found_error
    return self.r_display_error(error_code="404", error_message=response)
  File "/home/matt/formulae-capitains-nemo/formulae/nemo.py", line 458, in r_display_error
    return self.render(**{"template": 'main::404.html', 'message': error_message, 'url': dict()})
  File "/home/matt/envs/formulae-nemo/lib/python3.6/site-packages/flask_nemo/__init__.py", line 834, in render
    kwargs["cache_key"], kwargs["cache_key_i18n"] = self.make_cache_keys(request.endpoint, kwargs["url"])
  File "/home/matt/envs/formulae-nemo/lib/python3.6/site-packages/flask_nemo/__init__.py", line 810, in make_cache_keys
    i18n_cache_key = endpoint+"|"+"|".join([kwargs[k] for k in keys])
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
127.0.0.1 - - [16/Jul/2018 13:34:15] "GET /fiel.pdf HTTP/1.1" 500 -
```

**Comment by sonofmun** [comment]
This suggests that the `request.endpoint` is returning `None`. I doubt it is from the `kwargs["url"]` since my UnknownCollection error works and it also sends and empty dictionary for `"url"`. It this is the case that it breaks because the of the `request.endpoint`, then maybe it should allow the calling function to pass an endpoint to it?

**Comment by sonofmun** [comment]
Something like: `endpoint = kwargs["endpoint"] or request.endpoint` (or perhaps the other way around?)

**Comment by sonofmun** [comment]
I can confirm that the problem is that `request.endpoint` is returning `None`. This is because the url that I am testing it with `/file.pdf` is not registered as a URL rule with my application, where the URL that triggers the UnknownCollection error comes from a registered URL rule. So perhaps this is something that should be solved on my side instead of the flask_nemo side.

**Comment by sonofmun** [comment]
I have figured this out, so I am closing it.
